/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NumberAddition;

/**
 *
 * @author L3000n100
 *
 */

public class NumberAdditionUI extends javax.swing.JFrame{

    /**
     * Creates new form NumberAdditionUI
     */
    public NumberAdditionUI() {
        initComponents();
        initOperationListener();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtxtfieldResult = new javax.swing.JTextField();
        jbtnSeven = new javax.swing.JButton();
        jbtnEight = new javax.swing.JButton();
        jbtnNine = new javax.swing.JButton();
        jbtnFour = new javax.swing.JButton();
        jbtnFive = new javax.swing.JButton();
        jbtnSix = new javax.swing.JButton();
        jbtnOne = new javax.swing.JButton();
        jbtnTwo = new javax.swing.JButton();
        jbtnThree = new javax.swing.JButton();
        jbtnZero = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnMultiply = new javax.swing.JButton();
        jbtnDivide = new javax.swing.JButton();
        jbtnEqual = new javax.swing.JButton();
        jbtnSubtract = new javax.swing.JButton();
        jbtnClear = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnDecimal = new javax.swing.JButton();
        jbtnAbout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculator"));
        jPanel1.setFont(new java.awt.Font("Segoe WP Semibold", 0, 14)); // NOI18N

        jtxtfieldResult.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtxtfieldResult.setToolTipText("");
        jtxtfieldResult.setName("jtxtfieldResult"); // NOI18N
        jtxtfieldResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfieldResultActionPerformed(evt);
            }
        });

        jbtnSeven.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnSeven.setText("7");
        jbtnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSevenActionPerformed(evt);
            }
        });

        jbtnEight.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnEight.setText("8");
        jbtnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEightActionPerformed(evt);
            }
        });

        jbtnNine.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnNine.setText("9");
        jbtnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNineActionPerformed(evt);
            }
        });

        jbtnFour.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnFour.setText("4");
        jbtnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFourActionPerformed(evt);
            }
        });

        jbtnFive.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnFive.setText("5");
        jbtnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFiveActionPerformed(evt);
            }
        });

        jbtnSix.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnSix.setText("6");
        jbtnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSixActionPerformed(evt);
            }
        });

        jbtnOne.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnOne.setText("1");
        jbtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOneActionPerformed(evt);
            }
        });

        jbtnTwo.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnTwo.setText("2");
        jbtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTwoActionPerformed(evt);
            }
        });

        jbtnThree.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnThree.setText("3");
        jbtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThreeActionPerformed(evt);
            }
        });

        jbtnZero.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnZero.setText("0");
        jbtnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZeroActionPerformed(evt);
            }
        });

        jbtnAdd.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnAdd.setText("+");

        jbtnMultiply.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnMultiply.setText("*");

        jbtnDivide.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnDivide.setText("/");

        jbtnEqual.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnEqual.setText("=");

        jbtnSubtract.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnSubtract.setText("-");

        jbtnClear.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnClear.setText("clear");
        jbtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClearActionPerformed(evt);
            }
        });

        jbtnExit.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnExit.setText("exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnDecimal.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnDecimal.setText(".");
        jbtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDecimalActionPerformed(evt);
            }
        });

        jbtnAbout.setFont(new java.awt.Font("Segoe WP Semibold", 1, 14)); // NOI18N
        jbtnAbout.setText("About");
        jbtnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAboutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDecimal))
                    .addComponent(jtxtfieldResult)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jbtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnTwo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnThree))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jbtnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jbtnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbtnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnDivide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jbtnMultiply, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnAbout)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnDecimal, jbtnEight, jbtnFive, jbtnFour, jbtnNine, jbtnOne, jbtnSeven, jbtnSix, jbtnThree, jbtnTwo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnAdd, jbtnClear, jbtnExit, jbtnSubtract});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtfieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnTwo)
                            .addComponent(jbtnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnDecimal, jbtnEight, jbtnFive, jbtnFour, jbtnNine, jbtnOne, jbtnSeven, jbtnSix, jbtnThree, jbtnTwo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnDivide, jbtnEqual});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnClear, jbtnExit});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbtnMultiply, jbtnSubtract});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtfieldResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfieldResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfieldResultActionPerformed

    private void jbtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClearActionPerformed
        clearTextField();
    }//GEN-LAST:event_jbtnClearActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAboutActionPerformed
        javax.swing.JOptionPane.showMessageDialog(rootPane, "This is a sample GUI Builder app program made for research purposes.\n\u00a9kramretsel", "About", 1);
    }//GEN-LAST:event_jbtnAboutActionPerformed

    private void jbtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOneActionPerformed
        digits = digits.equals("0") ? "1" : digits+"1";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnOneActionPerformed

    private void jbtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTwoActionPerformed
        digits = digits.equals("0") ? "2" : digits+"2";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnTwoActionPerformed

    private void jbtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThreeActionPerformed
        digits = digits.equals("0") ? "3" : digits+"3";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnThreeActionPerformed

    private void jbtnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFourActionPerformed
        digits = digits.equals("0") ? "4" : digits+"4";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnFourActionPerformed

    private void jbtnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFiveActionPerformed
        digits = digits.equals("0") ? "5" : digits+"5";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnFiveActionPerformed

    private void jbtnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSixActionPerformed
        digits = digits.equals("0") ? "6" : digits+"6";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnSixActionPerformed

    private void jbtnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSevenActionPerformed
        digits = digits.equals("0") ? "7" : digits+"7";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnSevenActionPerformed

    private void jbtnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEightActionPerformed
        digits = digits.equals("0") ? "8" : digits+"8";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnEightActionPerformed

    private void jbtnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNineActionPerformed
        digits = digits.equals("0") ? "9" : digits+"9";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnNineActionPerformed

    private void jbtnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZeroActionPerformed
        digits = digits.equals("0") ? "0" : digits+"0";
        jtxtfieldResult.setText(digits);
    }//GEN-LAST:event_jbtnZeroActionPerformed

    private void jbtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDecimalActionPerformed
        if(!(jtxtfieldResult.getText().contains("."))){
            digits += ".";
        }
    }//GEN-LAST:event_jbtnDecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberAdditionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberAdditionUI().setVisible(true);
            }
        });  
    }
    
    private int operation;
    private float num1, num2, result;
    private String digits = "";
    
    private void clearTextField(){
        digits = "";
        jtxtfieldResult.setText(digits);
    }
    
    private void initOperationListener(){
    jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOperation(evt);
            }
        });
    jbtnSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOperation(evt);
            }
        });
    jbtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOperation(evt);
            }
        });
    jbtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setOperation(evt);
            }
        });
    jbtnEqual.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt){
                performOperation(operation);
            }
        });
    }
    
    public void setOperation(java.awt.event.ActionEvent evt) {
        System.out.println("action performed");
        try{
            num1 = Float.parseFloat(jtxtfieldResult.getText());
        }catch(NumberFormatException ne){
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid input", "Error", 0);
            System.out.println(ne);
        }
        switch (evt.getActionCommand()) {
            case "+": operation = 1; break;
            case "-": operation = 2; break;
            case "*": operation = 3; break;
            case "/": operation = 4; break;
        }
        
        clearTextField();
    }
    
    private void performOperation(int operation){
        try{
            num2 = Float.parseFloat(jtxtfieldResult.getText());
        }catch(NumberFormatException ne){
            javax.swing.JOptionPane.showMessageDialog(rootPane, "Invalid input", "Error", 0);
            System.out.println(ne);
        }
        clearTextField(); 
        switch(operation){
            case 1: result = num1 + num2; break;
            case 2: result = num1 - num2; break;
            case 3: result = num1 * num2; break;
            case 4: result = num1 / num2; break;
        }
        jtxtfieldResult.setText(String.valueOf(result));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAbout;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnClear;
    private javax.swing.JButton jbtnDecimal;
    private javax.swing.JButton jbtnDivide;
    private javax.swing.JButton jbtnEight;
    private javax.swing.JButton jbtnEqual;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnFive;
    private javax.swing.JButton jbtnFour;
    private javax.swing.JButton jbtnMultiply;
    private javax.swing.JButton jbtnNine;
    private javax.swing.JButton jbtnOne;
    private javax.swing.JButton jbtnSeven;
    private javax.swing.JButton jbtnSix;
    private javax.swing.JButton jbtnSubtract;
    private javax.swing.JButton jbtnThree;
    private javax.swing.JButton jbtnTwo;
    private javax.swing.JButton jbtnZero;
    private javax.swing.JTextField jtxtfieldResult;
    // End of variables declaration//GEN-END:variables

    
}
